# No observability module.
components:
  dashboard:
    dsc:
      managementState: Managed
services:
  monitoring:
    dependencies:
      clusterObservability: false
      opentelemetry: false
      tempo: false
    dsci:
      managementState: Removed
