apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Korrel8rServiceName}}-config
  namespace: {{.Namespace}}
  labels:
    platform.opendatahub.io/part-of: monitoring
data:
  korrel8r.yaml: |
    stores:
      - domain: k8s
{{- if .Metrics}}
      - domain: metric
        metric: {{.ThanosQuerierEndpoint}}
{{- end}}
{{- if .Traces}}
      - domain: trace
        tempoStack: {{.TempoQueryEndpoint}}/api/search
        certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
{{- end}}
{{- if .Logs}}
      - domain: log
        lokiStack: {{.LokiQueryEndpoint}}
        direct: true
        certificateAuthority: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
{{- end}}
    include:
      - /etc/korrel8r/rules/all.yaml
{{- if .Metrics}}
      - /etc/korrel8r/custom/rhoai-metrics.yaml
{{- end}}
    tuning:
      requestTimeout: {{.Korrel8rRequestTimeout}}
      sessionTimeout: {{.Korrel8rSessionTimeout}}
{{- if .Metrics}}
  rhoai-metrics.yaml: |
    rules:
      - name: PodToRHOAIMetric
        start:
          domain: k8s
          classes: [Pod]
        goal:
          domain: metric
        result:
          query: |-
            metric:metric:{exported_namespace="{{ "{{" }}.metadata.namespace{{ "}}" }}",exported_pod="{{ "{{" }}.metadata.name{{ "}}" }}"}
{{- end}}
