kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: data-science-thanos-querier-route
  namespace: {{.Namespace}}
  labels:
    app: thanos-querier
    app.kubernetes.io/name: thanos-querier
    app.kubernetes.io/component: querier
    app.kubernetes.io/part-of: data-science-monitoring
spec:
  path: /
  to:
    kind: Service
    name: data-science-thanos-querier-proxy
    weight: 100
  port:
    targetPort: https
  wildcardPolicy: None
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
